var master = [
    {title: "国税庁", url: "https://www.nta.go.jp/"},
    {title: "National Tax Agency JAPAN", url: "https://www.nta.go.jp/english/index.htm"},
    {title: "文字拡大・音声読み上げツール｜国税庁", url: "https://www.nta.go.jp/accessibility/tool.htm"},
    {title: "利用者別に調べる｜国税庁", url: "https://www.nta.go.jp/users/index.htm"},
    {title: "サイトマップ｜国税庁", url: "https://www.nta.go.jp/sitemap/index.htm"},
    {title: "国税庁", url: "https://www.nta.go.jp/index.htm"},
    {title: "税について調べる｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/index.htm"},
    {title: "申告手続・用紙｜国税庁", url: "https://www.nta.go.jp/taxes/tetsuzuki/index.htm"},
    {title: "納税・納税証明書手続｜国税庁", url: "https://www.nta.go.jp/taxes/nozei/index.htm"},
    {title: "税理士に関する情報｜国税庁", url: "https://www.nta.go.jp/taxes/zeirishi/index.htm"},
    {title: "お酒に関する情報｜国税庁", url: "https://www.nta.go.jp/taxes/sake/index.htm"},
    {title: "税の学習コーナー｜国税庁", url: "https://www.nta.go.jp/taxes/kids/index.htm"},
    {title: "パンフレット・手引｜国税庁", url: "https://www.nta.go.jp/publication/pamph/01.htm"},
    {title: "国税庁ホームページ", url: "https://www.nta.go.jp/publication/webtaxtv/index.htm"},
    {title: "出版物｜国税庁", url: "https://www.nta.go.jp/publication/book/index.htm"},
    {title: "統計情報｜国税庁", url: "https://www.nta.go.jp/publication/statistics/index.htm"},
    {title: "点字広報誌「私たちの税金」（平成29年度版）｜国税庁", url: "https://www.nta.go.jp/publication/tenji/index.htm"},
    {title: "法令解釈通達｜国税庁", url: "https://www.nta.go.jp/law/tsutatsu/menu.htm"},
    {title: "その他法令解釈に関する情報｜国税庁", url: "https://www.nta.go.jp/law/joho-zeikaishaku/sonota/sonota.htm"},
    {title: "事務運営指針｜国税庁", url: "https://www.nta.go.jp/law/jimu-unei/jimu.htm"},
    {title: "国税庁告示｜国税庁", url: "https://www.nta.go.jp/law/kokuji/kokuji.htm"},
    {title: "文書回答事例｜国税庁", url: "https://www.nta.go.jp/law/bunshokaito/01.htm"},
    {title: "質疑応答事例｜国税庁", url: "https://www.nta.go.jp/law/shitsugi/01.htm"},
    {title: "トピックス一覧｜国税庁", url: "https://www.nta.go.jp/information/news/index.htm"},
    {title: "報道発表", url: "https://www.nta.go.jp/information/release/index.htm"},
    {title: "パブリックコメント｜国税庁", url: "https://www.nta.go.jp/information/consulation/sake_index.htm"},
    {title: "調達情報・公売情報｜国税庁", url: "https://www.nta.go.jp/information/procurement/index.htm"},
    {title: "不審な電話や振り込め詐欺にご注意を｜国税庁", url: "https://www.nta.go.jp/information/attention/attention.htm"},
    {title: "その他のお知らせ｜国税庁", url: "https://www.nta.go.jp/information/other/shinkoku.htm"},
    {title: "国税庁の概要｜国税庁", url: "https://www.nta.go.jp/about/introduction/index.htm"},
    {title: "組織（国税局・税務署等）｜国税庁", url: "https://www.nta.go.jp/about/organization/index.htm"},
    {title: "採用情報｜国税庁", url: "https://www.nta.go.jp/about/recruitment/index.htm"},
    {title: "国税庁の実績の評価｜国税庁", url: "https://www.nta.go.jp/about/evaluation/01.htm"},
    {title: "審議会・研究会等｜国税庁", url: "https://www.nta.go.jp/about/council/kenkyu.htm"},
    {title: "情報公開｜国税庁", url: "https://www.nta.go.jp/about/disclosure/01.htm"},
    {title: "開示請求の手続｜国税庁", url: "https://www.nta.go.jp/about/disclosure/tetsuzuki/01.htm"},
    {title: "情報公開・個人情報保護窓口｜国税庁", url: "https://www.nta.go.jp/about/disclosure/madoguchi/index.htm"},
    {title: "国税庁・税務大学校（地方研修所を除く）・国税不服審判所（支部を除く）｜情報公開・個人情報保護窓口｜情報公開｜国税庁", url: "https://www.nta.go.jp/about/disclosure/madoguchi/cho.htm"},
    {title: "国税庁等について｜国税庁", url: "https://www.nta.go.jp/about/index.htm"},
    {title: "税務署の所在地などを知りたい方｜国税庁", url: "https://www.nta.go.jp/about/organization/access/map.htm"},
    {title: "国税に関するご相談について｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/sodan/denwa-sodan/index.htm"},
    {title: "税の相談｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/sodan/index.htm"},
    {title: "税についての上手な調べ方｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/shirabekata/info.htm"},
    {title: "タックスアンサー（よくある税の質問）｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/taxanswer/index2.htm"},
    {title: "東日本大震災により被害を受けた場合等の税金の取扱いについて｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/saigai/higashinihon/tokurei/zeikin.htm"},
    {title: "災害関連情報｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/saigai/index.htm"},
    {title: "災害等にあったとき｜国税庁", url: "https://www.nta.go.jp/publication/pamph/koho/kurashi/html/04_4.htm"},
    {title: "パンフレット「暮らしの税情報」（平成29年度版）｜国税庁", url: "https://www.nta.go.jp/publication/pamph/koho/kurashi/index.htm"},
    {title: "社会保障・税番号制度（マイナンバー制度）の導入｜国税庁", url: "https://www.nta.go.jp/publication/pamph/koho/kurashi/html/00_1.htm"},
    {title: "社会保障・税番号制度＜マイナンバー＞について｜国税庁", url: "https://www.nta.go.jp/taxes/tetsuzuki/mynumberinfo/index.htm"},
    {title: "国税の番号制度に関する情報｜国税庁", url: "https://www.nta.go.jp/taxes/tetsuzuki/mynumberinfo/jyoho/index.htm"},
    {title: "社会保障・税番号(マイナンバー)制度の概要について｜国税庁", url: "https://www.nta.go.jp/taxes/tetsuzuki/mynumberinfo/gaiyo.htm"},
    {title: "税の情報・手続・用紙｜国税庁", url: "https://www.nta.go.jp/taxes/index.htm"},
    {title: "所得税（確定申告書等作成コーナー）｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/shinkoku/kakutei.htm"},
    {title: "【OS】WindowsVista以前・Android4.4以前・【ブラウザ】IE9以前をご利用の方へ｜国税庁", url: "https://www.nta.go.jp/information/news/tls/tls.htm"},
    {title: "報道発表資料（プレスリリース）目次｜国税庁", url: "https://www.nta.go.jp/information/release/kokuzeicho/press.htm"},
    {title: "平成29年分の確定申告においてご留意いただきたい事項（平成30年1月）｜国税庁", url: "https://www.nta.go.jp/information/release/kokuzeicho/2018/shinkoku/index.htm"},
    {title: "No.1120&emsp;医療費を支払ったとき（医療費控除）｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/taxanswer/shotoku/1120.htm"},
    {title: "所得税｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/taxanswer/shotoku/shotoku.htm"},
    {title: "夫婦と税金｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/taxanswer/shotoku/shoto301.htm"},
    {title: "No.1800&emsp;パート収入はいくらまで税金がかからないか｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/taxanswer/shotoku/1800.htm"},
    {title: "No.1400&emsp;給与所得｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/taxanswer/shotoku/1400.htm"},
    {title: "No.2508　給与所得となるもの｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/taxanswer/gensen/2508.htm"},
    {title: "源泉所得税｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/taxanswer/gensen/gensen.htm"},
    {title: "給与と源泉徴収｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/taxanswer/gensen/gensen31.htm"},
    {title: "No.2502&emsp;源泉徴収義務者とは｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/taxanswer/gensen/2502.htm"},
    {title: "No.2020&emsp;確定申告｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/taxanswer/shotoku/2020.htm"},
    {title: "確定申告書、青色申告決算書、収支内訳書等｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/shinkoku/yoshiki/01/shinkokusho/02.htm"},
    {title: "確定申告書等｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/shinkoku/yoshiki/01/01.htm"},
    {title: "確定申告書付表等｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/shinkoku/yoshiki/01/fuhyo/03.htm"},
    {title: "PDFファイルが開けない・印刷できないなどの場合は、こちらをご覧ください｜国税庁", url: "https://www.nta.go.jp/taxes/tetsuzuki/shinsei/annai/toiawase/1679/01.htm"},
    {title: "申告・申請・届出等、用紙（手続の案内・様式）｜国税庁", url: "https://www.nta.go.jp/taxes/tetsuzuki/shinsei/index.htm"},
    {title: "相続税｜国税庁", url: "https://www.nta.go.jp/taxes/tetsuzuki/shinsei/shinkoku/sozoku/sozoku.htm"},
    {title: "確定申告等情報｜国税庁", url: "https://www.nta.go.jp/taxes/tetsuzuki/shinkoku/index.htm"},
    {title: "贈与税（贈与税の申告書作成コーナー）｜国税庁", url: "https://www.nta.go.jp/taxes/tetsuzuki/shinsei/shinkoku/zoyo/souzoku.htm"},
    {title: "平成29年分贈与税の申告のしかた｜国税庁", url: "https://www.nta.go.jp/taxes/tetsuzuki/shinsei/shinkoku/zoyo/tebiki2017/01.htm"},
    {title: "平成29年分贈与税の申告書等の様式一覧｜国税庁", url: "https://www.nta.go.jp/taxes/tetsuzuki/shinsei/shinkoku/zoyo/yoshiki2017/01.htm"},
    {title: "税目別情報｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/zeimokubetsu/index.htm"},
    {title: "所得税｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/zeimokubetsu/shotoku.htm"},
    {title: "税大講本｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/kohon/index.htm"},
    {title: "税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/index.htm"},
    {title: "National Tax College Japan", url: "https://www.nta.go.jp/about/organization/ntc/english/index.htm"},
    {title: "Notice on Copyright and Other Related Matters Regarding this Web Site｜National Tax Agency", url: "https://www.nta.go.jp/english/notice/index.htm"},
    {title: "Individual Income Tax｜国税庁", url: "https://www.nta.go.jp/english/taxes/individual/index.htm"},
    {title: "Corporation Income Tax", url: "https://www.nta.go.jp/english/taxes/corporation/index.htm"},
    {title: "Withholding Tax | National Tax Agency", url: "https://www.nta.go.jp/english/taxes/withholing/index.htm"},
    {title: "International Taxation", url: "https://www.nta.go.jp/english/taxes/international/index.htm"},
    {title: "Indirect Taxes", url: "https://www.nta.go.jp/english/taxes/indirect/index.htm"},
    {title: "Information on Liquor Administration | National Tax Agency", url: "https://www.nta.go.jp/english/taxes/liquor_administration/index.htm"},
    {title: "About The Corporate Number | National Tax Agency", url: "https://www.nta.go.jp/english/taxes/corporate_number/index.htm"},
    {title: "Information for main notifications, etc. l National Tax Agency", url: "https://www.nta.go.jp/english/taxes/main_notifications/index.htm"},
    {title: "About the Office of Tax Collections Call Center (&quot;Tax Payment Call Center&quot;) | Contents | National Tax Agency", url: "https://www.nta.go.jp/english/taxes/call_center/index.htm"},
    {title: "Others", url: "https://www.nta.go.jp/english/taxes/others/index.htm"},
    {title: "Tax Statistics", url: "https://www.nta.go.jp/english/publication/statistics/index.htm"},
    {title: "National Tax Agency Report", url: "https://www.nta.go.jp/english/publication/agency_report/index.htm"},
    {title: "MAP Report", url: "https://www.nta.go.jp/english/publication/map_report/index.htm"},
    {title: "Press Release | National Tax Agency", url: "https://www.nta.go.jp/english/release/press.htm"},
    {title: "About US｜National Tax Agency JAPAN", url: "https://www.nta.go.jp/english/about/index.htm"},
    {title: "Organization｜National Tax Agency JAPAN", url: "https://www.nta.go.jp/english/about/organization/index.htm"},
    {title: "Related Sites｜National Tax Agency JAPAN", url: "https://www.nta.go.jp/english/about/link/index.htm"},
    {title: "Contact US｜National Tax Agency JAPAN", url: "https://www.nta.go.jp/english/contact/index.htm"},
    {title: "Information for Taxpayers｜National Tax Agency JAPAN", url: "https://www.nta.go.jp/english/taxes/index.htm"},
    {title: "Publication｜National Tax Agency JAPAN", url: "https://www.nta.go.jp/english/publication/index.htm"},
    {title: "EOI Report", url: "https://www.nta.go.jp/english/eoi_report/index.htm"},
    {title: "SNS｜National Tax Agency JAPAN", url: "https://www.nta.go.jp/english/sns/index.htm"},
    {title: "指定されたページを表示できませんでした", url: "https://www.nta.go.jp/publication/webtaxtv/video_for_foreinger.htm"},
    {title: "個人の方｜国税庁", url: "https://www.nta.go.jp/users/kojin/index.htm"},
    {title: "その他目次｜国税庁", url: "https://www.nta.go.jp/law/joho-zeikaishaku/sonota/sonota-mokuji.htm"},
    {title: "税務調査手続について（国税通則法第7章の2（国税の調査）関係）｜国税庁", url: "https://www.nta.go.jp/law/joho-zeikaishaku/sonota/sozokuchosatetsuzuki/index.htm"},
    {title: "税務調査手続関係　個別通達目次｜国税庁", url: "https://www.nta.go.jp/law/tsutatsu/kobetsu/zeimuchosa/zeimuchosa.htm"},
    {title: "国税通則法第7章の2（国税の調査）関係通達の制定について（法令解釈通達）｜国税庁", url: "https://www.nta.go.jp/law/tsutatsu/kobetsu/zeimuchosa/120912/index.htm"},
    {title: "第1章　法第74条の2〜法第74条の6関係（質問検査権）｜国税庁", url: "https://www.nta.go.jp/law/tsutatsu/kobetsu/zeimuchosa/120912/01.htm"},
    {title: "法令等｜国税庁", url: "https://www.nta.go.jp/law/index.htm"},
    {title: "相続税・贈与税目次｜国税庁", url: "https://www.nta.go.jp/law/joho-zeikaishaku/sozoku/souzoku.htm"},
    {title: "「租税特別措置法（相続税法の特例関係）の取扱いについて」等の一部改正について（法令解釈通達）のあらまし（情報）｜国税庁", url: "https://www.nta.go.jp/law/joho-zeikaishaku/sozoku/160205/index.htm"},
    {title: "法人の方｜国税庁", url: "https://www.nta.go.jp/users/hojin/index.htm"},
    {title: "国税庁ホームページの使い方｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/search/help/index.htm"},
    {title: "国際税務関係情報｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/kokusai/index.htm"},
    {title: "国際戦略トータルプラン｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/kokusai/strategy/index.htm"},
    {title: "国際戦略トータルプラン −国際課税の取組の現状と今後の方向−｜国税庁", url: "https://www.nta.go.jp/information/release/kokuzeicho/2016/kokusai_kazei/index.htm"},
    {title: "平成18年3月以前のパブリックコメント案件｜国税庁", url: "https://www.nta.go.jp/information/consulation/ichiran/01.htm"},
    {title: "「酒税法及び酒類行政関係法令等解釈通達の一部改正(案)」に対する意見募集について｜国税庁", url: "https://www.nta.go.jp/information/consulation/ichiran/060123/01.htm"},
    {title: "酒税法及び酒類行政関係法令等解釈通達の一部改正(案)｜国税庁", url: "https://www.nta.go.jp/information/consulation/ichiran/060123/02.htm"},
    {title: "現行の酒類小売業免許の区分による免許の付与等の取扱いの概要｜国税庁", url: "https://www.nta.go.jp/information/consulation/ichiran/060123/03.htm"},
    {title: "源泉徴収義務者の方｜国税庁", url: "https://www.nta.go.jp/users/gensen/index.htm"},
    {title: "配偶者控除及び配偶者特別控除の見直しについて｜国税庁", url: "https://www.nta.go.jp/users/gensen/haigusya/index.htm"},
    {title: "大規模法人向けの情報を調べる｜国税庁", url: "https://www.nta.go.jp/users/hojin/daikibo_hojin.htm"},
    {title: "国税庁の機構｜国税庁", url: "https://www.nta.go.jp/about/introduction/shokai/kiko/kikou.htm"},
    {title: "バーチャルガイド国税局・税務署の仕事｜国税庁", url: "https://www.nta.go.jp/about/recruitment/work/index.htm"},
    {title: "札幌国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/sapporo/index.htm"},
    {title: "国税専門官　セミナー開催案内｜国税庁", url: "https://www.nta.go.jp/about/organization/sapporo/recruitment/jinji/setsumeikai.htm"},
    {title: "採用案内｜国税庁", url: "https://www.nta.go.jp/about/organization/sapporo/recruitment/index.htm"},
    {title: "職員｜国税庁", url: "https://www.nta.go.jp/about/organization/sapporo/recruitment/shokuin_index.htm"},
    {title: "人事・研修制度｜国税庁", url: "https://www.nta.go.jp/about/recruitment/kokusen/kenshu/03.htm"},
    {title: "専門官基礎研修｜研修｜税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/kenshu/senmonkan_kiso.htm"},
    {title: "研修｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/kenshu/index.htm"},
    {title: "普通科｜研修｜税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/kenshu/futsuu.htm"},
    {title: "税務大学校関東信越研修所｜所在地｜税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/shozaichi/shisetsu/kanshin.htm"},
    {title: "所在地｜所在地｜税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/shozaichi/index.htm"},
    {title: "和光校舎紹介｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/shozaichi/wakou.htm"},
    {title: "仙台国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/index.htm"},
    {title: "事務センターのご案内｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/shokai/jimu_center.htm"},
    {title: "仙台国税局の紹介｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/shokai/index.htm"},
    {title: "仙台国税局の所在地・案内図｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/shokai/annai.htm"},
    {title: "庁舎のバリアフリー施設一覧（平成29年3月現在）｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/location/barrier_free_miyagi.htm"},
    {title: "税務署所在地・案内｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/location/index.htm"},
    {title: "税務署所在地・案内（青森県）｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/location/aomori.htm"},
    {title: "青森税務署｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/location/aomori/aomori/index.htm"},
    {title: "国税に関するご相談について｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/sodan/denwa-sodan/case1.htm"},
    {title: "税についての相談窓口｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/shirabekata/9200.htm"},
    {title: "税務署所在地・案内（北海道）｜国税庁", url: "https://www.nta.go.jp/about/organization/sapporo/location/index.htm"},
    {title: "国税に関するご相談について｜国税庁", url: "https://www.nta.go.jp/taxes/shiraberu/sodan/denwa-sodan/case2.htm"},
    {title: "［手続名］国税の納付手続（納期限・振替日・納付方法）｜国税庁", url: "https://www.nta.go.jp/taxes/nozei/nofu/01.htm"},
    {title: "納税証明書及び納税手続関係｜国税庁", url: "https://www.nta.go.jp/taxes/nozei/mokuji.htm"},
    {title: "［手続名］納税証明書の交付請求手続｜国税庁", url: "https://www.nta.go.jp/taxes/nozei/nozei-shomei/01.htm"},
    {title: "［手続名］源泉徴収に係る所得税及び復興特別所得税の納税証明願｜国税庁", url: "https://www.nta.go.jp/taxes/tetsuzuki/shinsei/annai/gensen/annai/1648_31.htm"},
    {title: "税務手続の案内｜国税庁", url: "https://www.nta.go.jp/taxes/tetsuzuki/shinsei/annai/yousiki.htm"},
    {title: "番号制度に係る税務署への申請書等の提出に当たってのお願い｜国税庁", url: "https://www.nta.go.jp/taxes/tetsuzuki/mynumberinfo/zeimusho_shinseisho.htm"},
    {title: "平成28年度税制改正によるマイナンバー（個人番号）記載対象書類の見直しについて（改正内容のお知らせ）｜国税庁", url: "https://www.nta.go.jp/taxes/tetsuzuki/mynumberinfo/jizenjyoho/kaisei/280401.htm"},
    {title: "番号制度概要に関するFAQ｜国税庁", url: "https://www.nta.go.jp/taxes/tetsuzuki/mynumberinfo/FAQ/gaiyou_qa.htm"},
    {title: "社会保障・税番号制度＜マイナンバー＞FAQ（平成30年1月4日現在）｜国税庁", url: "https://www.nta.go.jp/taxes/tetsuzuki/mynumberinfo/FAQ/index.htm"},
    {title: "番号制度概要に関するFAQ｜国税庁", url: "https://www.nta.go.jp/taxes/tetsuzuki/mynumberinfo/FAQ/gaiyou.htm"},
    {title: "延納・物納申請等｜国税庁", url: "https://www.nta.go.jp/taxes/nozei/enno-butsuno/01.htm"},
    {title: "非上場株式等の相続税の納税猶予の適用を受ける方があわせて延納申請をされる場合の取扱いについて（平成22年4月1日以降相続開始分）｜国税庁", url: "https://www.nta.go.jp/taxes/nozei/enno-butsuno/sozoku.htm"},
    {title: "延滞税の計算方法｜国税庁", url: "https://www.nta.go.jp/taxes/nozei/entaizei/keisan/entai.htm"},
    {title: "延滞税の割合｜国税庁", url: "https://www.nta.go.jp/taxes/nozei/entaizei/keisan/entai_wariai.htm"},
    {title: "税理士制度｜国税庁", url: "https://www.nta.go.jp/taxes/zeirishi/zeirishiseido/seido.htm"},
    {title: "税理士制度｜国税庁", url: "https://www.nta.go.jp/taxes/zeirishi/zeirishiseido/seido2.htm"},
    {title: "日本税理士会連合会｜国税庁", url: "https://www.nta.go.jp/taxes/zeirishi/zeirishiseido/rengokai/rengou.htm"},
    {title: "税理士試験｜国税庁", url: "https://www.nta.go.jp/taxes/zeirishi/zeirishishiken/zeirishi.htm"},
    {title: "税理士試験の概要｜国税庁", url: "https://www.nta.go.jp/taxes/zeirishi/zeirishishiken/gaiyo/gaiyou.htm"},
    {title: "税理士等に対する懲戒処分等｜国税庁", url: "https://www.nta.go.jp/taxes/zeirishi/chokai/chokai.htm"},
    {title: "1　税理士・税理士法人に対する懲戒処分等の考え方（平成27年4月1日以後にした不正行為に係る懲戒処分等に適用）｜国税庁", url: "https://www.nta.go.jp/taxes/zeirishi/chokai/shobun/index.htm"},
    {title: "税理士をお探しの方へ｜国税庁", url: "https://www.nta.go.jp/taxes/zeirishi/search/search.htm"},
    {title: "税理士関係法令等・Q&amp;A｜国税庁", url: "https://www.nta.go.jp/taxes/zeirishi/zeirishiseido/qa.htm"},
    {title: "2　税理士・税理士法人に対する懲戒処分等の考え方　（平成27年3月31日以前にした不正行為に係る懲戒処分等に適用）｜国税庁", url: "https://www.nta.go.jp/taxes/zeirishi/chokai/shobun/20331.htm"},
    {title: "所在地情報｜国税庁", url: "https://www.nta.go.jp/about/organization/access/location/map.htm"},
    {title: "ご意見・ご要望｜国税庁", url: "https://www.nta.go.jp/iken/mail.htm"},
    {title: "302 Found", url: "https://www.nta.go.jp/suggestion/johoteikyo/input_form.htm"},
    {title: "納税者支援調整官｜国税庁の機構｜国税庁概要・採用｜国税庁", url: "https://www.nta.go.jp/about/introduction/shokai/kiko/nozeishashien/index.htm"},
    {title: "札幌国税局｜納税者支援調整官｜国税庁の機構｜国税庁概要・採用｜国税庁", url: "https://www.nta.go.jp/about/introduction/shokai/kiko/nozeishashien/sapporo.htm"},
    {title: "札幌国税局の所在地・案内図｜国税庁", url: "https://www.nta.go.jp/about/organization/sapporo/shokai/annai.htm"},
    {title: "札幌国税局の紹介｜国税庁", url: "https://www.nta.go.jp/about/organization/sapporo/shokai/index.htm"},
    {title: "集中電話催告センター室（納税コールセンター）のご案内｜国税庁", url: "https://www.nta.go.jp/about/organization/callcenter/index.htm"},
    {title: "関東信越国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/kantoshinetsu/index.htm"},
    {title: "「関東信越国税局　文書照会センター」のご案内｜国税庁", url: "https://www.nta.go.jp/about/organization/kantoshinetsu/topics/bunshoshokai_center/index.htm"},
    {title: "東京国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/tokyo/index.htm"},
    {title: "職場説明会等日程一覧｜国税庁", url: "https://www.nta.go.jp/about/organization/tokyo/recruitment/setsumeikai/01.htm"},
    {title: "採用案内｜国税庁", url: "https://www.nta.go.jp/about/organization/tokyo/recruitment/index.htm"},
    {title: "職員｜国税庁", url: "https://www.nta.go.jp/about/organization/tokyo/recruitment/staff.htm"},
    {title: "税務職員採用試験｜国税庁", url: "https://www.nta.go.jp/about/recruitment/zeimushoku/03.htm"},
    {title: "業務内容｜国税庁", url: "https://www.nta.go.jp/about/recruitment/zeimushoku/gyomu/index.htm"},
    {title: "金沢国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/kanazawa/index.htm"},
    {title: "課税部事務処理センター（課税センター）の設置について｜国税庁", url: "https://www.nta.go.jp/about/organization/kanazawa/topics/kcenter/index.htm"},
    {title: "名古屋国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/nagoya/index.htm"},
    {title: "職場説明会｜税務職員採用試験｜名古屋国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/nagoya/recruitment/syokuin/saiyo03/setsumeikai.htm"},
    {title: "採用案内｜国税庁", url: "https://www.nta.go.jp/about/organization/nagoya/recruitment/index.htm"},
    {title: "採用案内｜国税庁", url: "https://www.nta.go.jp/about/organization/nagoya/recruitment/syokuin/index.htm"},
    {title: "税務署所在地・案内｜国税庁", url: "https://www.nta.go.jp/about/organization/nagoya/location/index.htm"},
    {title: "税務署所在地・案内（岐阜県）｜国税庁", url: "https://www.nta.go.jp/about/organization/nagoya/location/gifu.htm"},
    {title: "大垣税務署｜国税庁", url: "https://www.nta.go.jp/about/organization/nagoya/location/gifu/ogaki/index.htm"},
    {title: "大垣税務署のご案内｜国税庁", url: "https://www.nta.go.jp/about/organization/nagoya/location/gifu/ogaki/data.htm"},
    {title: "大阪国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/osaka/index.htm"},
    {title: "「税務署事務処理センター」の設置についてのお知らせ｜国税庁", url: "https://www.nta.go.jp/about/organization/osaka/topics/jimushori-center/07170811.htm"},
    {title: "来署によるご相談は、事前予約をお願いします｜国税庁", url: "https://www.nta.go.jp/about/organization/osaka/topics/jizenyoyaku/index.htm"},
    {title: "税務署所在地・案内｜国税庁", url: "https://www.nta.go.jp/about/organization/osaka/location/index.htm"},
    {title: "税務署所在地・案内（滋賀県）｜国税庁", url: "https://www.nta.go.jp/about/organization/osaka/location/shiga.htm"},
    {title: "今津税務署｜国税庁", url: "https://www.nta.go.jp/about/organization/osaka/location/shiga/imazu/index.htm"},
    {title: "今津税務署｜国税庁", url: "https://www.nta.go.jp/about/organization/osaka/topics/kakutei_shinkoku/kaijyo/shiga/imazu.htm"},
    {title: "広島国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/hiroshima/index.htm"},
    {title: "「国税専門官」業務説明会のご案内｜国税庁", url: "https://www.nta.go.jp/about/organization/hiroshima/recruitment/senmonkan/08180282.htm"},
    {title: "採用案内｜国税庁", url: "https://www.nta.go.jp/about/organization/hiroshima/recruitment/index.htm"},
    {title: "国税専門官採用試験(大学卒業程度)｜国税庁", url: "https://www.nta.go.jp/about/organization/hiroshima/recruitment/kokusentop.htm"},
    {title: "試験概要｜国税庁", url: "https://www.nta.go.jp/about/recruitment/kokusen/shiken/test_02.htm"},
    {title: "平成30年度　国税専門官採用試験受験申込を開始します｜国税庁", url: "https://www.nta.go.jp/about/recruitment/kokusen/shiken/test_h30.htm"},
    {title: "高松国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/takamatsu/index.htm"},
    {title: "職員採用案内等｜国税庁", url: "https://www.nta.go.jp/about/organization/takamatsu/recruitment/shokuin_saiyo.htm"},
    {title: "採用案内｜国税庁", url: "https://www.nta.go.jp/about/organization/takamatsu/recruitment/index.htm"},
    {title: "非常勤職員採用案内｜国税庁", url: "https://www.nta.go.jp/about/organization/takamatsu/recruitment/parttime/kyoku.htm"},
    {title: "高松国税局の所在地・案内図｜国税庁", url: "https://www.nta.go.jp/about/organization/takamatsu/shokai/annai.htm"},
    {title: "高松局税局の紹介｜国税庁", url: "https://www.nta.go.jp/about/organization/takamatsu/shokai/index.htm"},
    {title: "福岡国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/fukuoka/index.htm"},
    {title: "職場セミナー等のお知らせ｜国税庁", url: "https://www.nta.go.jp/about/organization/fukuoka/recruitment/guidance.htm"},
    {title: "採用案内｜国税庁", url: "https://www.nta.go.jp/about/organization/fukuoka/recruitment/index.htm"},
    {title: "国税専門官採用試験｜国税庁", url: "https://www.nta.go.jp/about/organization/fukuoka/recruitment/kokuzeisemmonkan.htm"},
    {title: "専攻税法研修｜研修｜税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/kenshu/senkou_zeihou.htm"},
    {title: "熊本国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/kumamoto/index.htm"},
    {title: "平成29年分熊本国税局管内申告相談会場等について｜国税庁", url: "https://www.nta.go.jp/about/organization/kumamoto/release/h29/shinkoku_jokyo/shinkoku_soudan.htm"},
    {title: "報道発表資料（プレスリリース）目次｜国税庁", url: "https://www.nta.go.jp/about/organization/kumamoto/release/index.htm"},
    {title: "平成29年分の所得税等、消費税及び贈与税の確定申告について（報道発表資料）｜国税庁", url: "https://www.nta.go.jp/about/organization/kumamoto/release/h29/shinkoku_jokyo/index.htm"},
    {title: "平成28年熊本地震により被害を受けられた方を対象とする申告書事前作成会について｜国税庁", url: "https://www.nta.go.jp/about/organization/kumamoto/release/h29/shinkoku_jokyo/shinkoku_sakusei.htm"},
    {title: "平成29年分&emsp;申告相談会場の開設状況等について（熊本西）｜国税庁", url: "https://www.nta.go.jp/about/organization/kumamoto/topics/shinkoku_soudan/kumamoto/kumamotonishi.htm"},
    {title: "沖縄国税事務所｜国税庁", url: "https://www.nta.go.jp/about/organization/okinawa/index.htm"},
    {title: "平成29年分確定申告会場のお知らせ｜国税庁", url: "https://www.nta.go.jp/about/organization/okinawa/topics/shinkoku/index.htm"},
    {title: "国税庁で働くということ｜国税庁", url: "https://www.nta.go.jp/about/recruitment/outline/index.htm"},
    {title: "総合職（事務系）採用｜国税庁", url: "https://www.nta.go.jp/about/recruitment/jimukei/01_1.htm"},
    {title: "業務内容｜国税庁", url: "https://www.nta.go.jp/about/recruitment/jimukei/gyomu/index.htm"},
    {title: "総合職（技術系）採用｜国税庁", url: "https://www.nta.go.jp/about/recruitment/gijyutsu/01_2.htm"},
    {title: "業務内容｜国税庁", url: "https://www.nta.go.jp/about/recruitment/gijyutsu/gyomu/index.htm"},
    {title: "総合職（院卒法務区分）採用｜国税庁", url: "https://www.nta.go.jp/about/recruitment/insotsu/index.htm"},
    {title: "国税専門官試験採用｜国税庁", url: "https://www.nta.go.jp/about/recruitment/kokusen/02.htm"},
    {title: "業務内容｜国税庁", url: "https://www.nta.go.jp/about/recruitment/kokusen/gyomu/01_1.htm"},
    {title: "経験者採用試験｜国税庁", url: "https://www.nta.go.jp/about/recruitment/keikensha/index.htm"},
    {title: "業務内容｜国税庁", url: "https://www.nta.go.jp/about/recruitment/keikensha/gyomu/index.htm"},
    {title: "国税庁非常勤職員（アルバイト）募集案内｜国税庁", url: "https://www.nta.go.jp/about/recruitment/part_time/04.htm"},
    {title: "各国税局の採用情報｜国税庁", url: "https://www.nta.go.jp/about/recruitment/link.htm"},
    {title: "採用案内｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/recruitment/index.htm"},
    {title: "国税専門官採用試験｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/recruitment/semmon.htm"},
    {title: "先輩からのメッセージ｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/recruitment/sempaimesseji/sempaimesseji.htm"},
    {title: "税のスペシャリストとして｜先輩からのメッセージ｜仙台国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/recruitment/sempaimesseji/message_a.htm"},
    {title: "個人情報の保護｜国税庁", url: "https://www.nta.go.jp/about/disclosure/kojinjoho/02.htm"},
    {title: "開示請求等の手続｜国税庁", url: "https://www.nta.go.jp/anout/disclosure/tetsuzuki-kojinjoho/03.htm"},
    {title: "関連リンク｜国税庁", url: "https://www.nta.go.jp/link/link.htm"},
    {title: "指定されたページを表示できませんでした", url: "https://www.nta.go.jp/accessibility/index.htm"},
    {title: "利用規約・免責事項・著作権｜国税庁", url: "https://www.nta.go.jp/chuijiko/copy.htm"},
    {title: "国税庁ホームページ利用規約｜国税庁", url: "https://www.nta.go.jp/chuijiko/riyokiyaku.htm"},
    {title: "税に関するシンボルマークについて｜国税庁", url: "https://www.nta.go.jp/chuijiko/tax_symbol.htm"},
    {title: "国税庁ホームページにおける個人情報保護方針｜国税庁", url: "https://www.nta.go.jp/privacy_policy/hogo.htm"},
    {title: "ウェブアクセシビリティ試験結果｜国税庁", url: "https://www.nta.go.jp/accessibility/result2015/index.htm"},
    {title: "国税庁ウェブアクセシビリティ方針｜国税庁", url: "https://www.nta.go.jp/web_accessbillity/index.htm"},
    {title: "国税庁ホームページの試験結果｜国税庁", url: "https://www.nta.go.jp/accessibility/result2015/nta.htm"},
    {title: "e-Taxホームページの試験結果｜国税庁", url: "https://www.nta.go.jp/accessibility/result2015/e-tax.htm"},
    {title: "財産評価基準書の試験結果｜国税庁", url: "https://www.nta.go.jp/accessibility/result2015/rosenka.htm"},
    {title: "公売情報ホームページの試験結果｜国税庁", url: "https://www.nta.go.jp/accessibility/result2015/koubai.htm"},
    {title: "官報公示内容｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/index2.htm"},
    {title: "個人情報の保護に関する法律の規定に基づき財務大臣から国税庁長官に委任された権限又は事務の一部を委任する件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/171127.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/170922.htm"},
    {title: "行政機関の保有する個人情報の保護に関する法律の規定に基づく国税庁長官の権限又は事務の一部を委任する件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/170705.htm"},
    {title: "個人情報の保護に関する法律の規定に基づき財務大臣から国税庁長官に委任された権限又は事務の一部を委任する件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/170530.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/160219.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/150216.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/140618.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/140129.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/130626.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/130603.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/130527.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/121219.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/121217.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/121002.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/120718.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/120619.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/111216.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/100705.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/100311.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/090312.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/081020.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/080812.htm"},
    {title: "国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/080508.htm"},
    {title: "○国税庁の保有する個人情報の開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/070904.htm"},
    {title: "○国税庁の保有する個人情報の開示請求手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/070215_4.htm"},
    {title: "○国税庁の保有する個人情報の開示請求手数料の納付を事務所において現金ですることができる事務所を定める件の一部を改正する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/060822_18.htm"},
    {title: "○個人情報の保護に関する法律の規定に基づき財務大臣から国税庁長官に委任された権限又は事務の一部を委任する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/050331_13.htm"},
    {title: "○行政機関の保有する個人情報の保護に関する法律の規定に基づく開示請求に係る手数料の納付を事務所において現金ですることができる事務所を定める件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/050325_8.htm"},
    {title: "○行政機関の保有する個人情報の保護に関する法律の規定に基づく国税庁長官の権限又は事務の一部を委任する件｜国税庁", url: "https://www.nta.go.jp/about/disclosure/koji-kojinjoho/050315_6.htm"},
    {title: "行政機関非識別加工情報に係る提案の募集等について｜国税庁", url: "https://www.nta.go.jp/about/disclosure/kojinjoho/h29_koji/index.htm"},
    {title: "ワーク・ライフ・バランス｜先輩からのメッセージ｜仙台国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/recruitment/sempaimesseji/message_b.htm"},
    {title: "同期との絆｜先輩からのメッセージ｜仙台国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/recruitment/sempaimesseji/message_c.htm"},
    {title: "職場の魅力｜先輩からのメッセージ｜仙台国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/recruitment/sempaimesseji/message_d.htm"},
    {title: "最後の砦・マルサ｜先輩からのメッセージ｜仙台国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/recruitment/sempaimesseji/message_e.htm"},
    {title: "高い専門性｜先輩からのメッセージ｜仙台国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/recruitment/sempaimesseji/message_f.htm"},
    {title: "組織一丸となって｜先輩からのメッセージ｜仙台国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/recruitment/sempaimesseji/message_g.htm"},
    {title: "実務に直結した研修｜先輩からのメッセージ｜仙台国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/recruitment/sempaimesseji/message_h.htm"},
    {title: "やりがいと充実感｜先輩からのメッセージ｜仙台国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/recruitment/sempaimesseji/message_i.htm"},
    {title: "育児支援制度の活用｜先輩からのメッセージ｜仙台国税局｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/recruitment/sempaimesseji/message_j.htm"},
    {title: "国税専門官（税務職員）セミナー・インターンシップ｜国税庁", url: "https://www.nta.go.jp/about/organization/sendai/recruitment/taxmansetsumeikai.htm"},
    {title: "専科｜研修｜税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/kenshu/senka.htm"},
    {title: "概要｜概要｜税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/intoroduction/index.htm"},
    {title: "研究活動｜研究活動｜税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/kenkyu/index.htm"},
    {title: "税務大学校論叢（ろんそう）｜研究活動｜税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/kenkyu/ronso.htm"},
    {title: "バックナンバー（税大論叢）｜研究活動｜税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/kenkyu/backnumber/ronsoIndex.htm"},
    {title: "税大論叢（84〜87号）｜研究活動｜税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/kenkyu/backnumber/ronso/24.htm"},
    {title: "更正処分の理由附記−行政手続法に定める処分理由と税法上の処分理由の異同について−｜論叢｜税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/kenkyu/ronsou/84/01/index.htm"},
    {title: "租税史料｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/sozei/index.htm"},
    {title: "租税史料ライブラリー｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/sozei/shiryou/index.htm"},
    {title: "検地と年貢｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/sozei/shiryou/library/01.htm"},
    {title: "寛文12年（1672年）御検地二付被仰渡候覚書｜検地と年貢｜税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/sozei/shiryou/library/01/01.htm"},
    {title: "元禄15年（1702年）下総国葛飾郡根本村田検地帳｜検地と年貢｜税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/sozei/shiryou/library/01/02.htm"},
    {title: "元禄3年(1690年) 新間御年貢納覚帳｜検地と年貢｜税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/sozei/shiryou/library/01/03.htm"},
    {title: "宝暦9年（1759年）　年貢割付状｜検地と年貢｜税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/sozei/shiryou/library/01/04.htm"},
    {title: "寛保元年（1741年）　年貢皆済目録｜検地と年貢｜税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/sozei/shiryou/library/01/05.htm"},
    {title: "当寅定免御取箇附｜検地と年貢｜税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/sozei/shiryou/library/01/06.htm"},
    {title: "国際協力｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/kokusai/index.htm"},
    {title: "指定されたページを表示できませんでした", url: "https://www.nta.go.jp/publication/webtaxtv/work.htm"},
    {title: "国際税務行政セミナー（ISTAX）上級｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/kokusai/istax_s/istax_s.htm"},
    {title: "2017　ISTAX上級｜国際協力｜税務大学校｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/kokusai/istax_s/2017.htm"},
    {title: "税務大学校の調達情報｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/index.htm"},
    {title: "政府調達情報｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu.htm"},
    {title: "政府調達情報|意見招請に関する公示|国税庁", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/20141023.htm"},
    {title: "非常勤職員の募集｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/parttime/index.htm"},
    {title: "302 Found", url: "https://www.nta.go.jp/ntc/suggestion/question/input_form.htm"},
    {title: "一般競争入札｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/110921.htm"},
    {title: "政府調達情報|意見招請に関する公示|国税庁", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/170621.htm"},
    {title: "平成30年度税務大学校通信研究『窓口英語Ⅰ』、『窓口英語』の実施委託業務", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/180301.htm"},
    {title: "161221-2", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/171221-2.htm"},
    {title: "税務大学校和光校舎および関東信越研修所において使用するガスの調達", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/170814.htm"},
    {title: "161221", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/161221-1.htm"},
    {title: "161221", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/171221-1.htm"},
    {title: "161228", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/171221-3.htm"},
    {title: "170501-2", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/170501-2.htm"},
    {title: "170501-1", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/170501-1.htm"},
    {title: "161221-2", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/170301.htm"},
    {title: "161221-2", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/161221-2.htm"},
    {title: "161228", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/161228.htm"},
    {title: "161116", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/161116.htm"},
    {title: "160901-2", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/160901-2.htm"},
    {title: "160502", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/160502.htm"},
    {title: "160121", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/160121.htm"},
    {title: "160112", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/160112.htm"},
    {title: "151116-1", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/151116-1.htm"},
    {title: "150821", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/150821.htm"},
    {title: "150501", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/150501.htm"},
    {title: "一般競争入札｜政府調達情報", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/140123-2.htm"},
    {title: "150123-2", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/150123-2.htm"},
    {title: "一般競争入札公告｜政府調達情報", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/140105.htm"},
    {title: "入札公告｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/seifu/koukoku/141211-3.htm"},
    {title: "競争入札の状況（物品役務等）｜国税庁", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin.htm"},
    {title: "平成30年度　税務大学校通信研修「韓国語Ⅰ」の研修実施委託", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/180323-3.htm"},
    {title: "平成30年度　税務大学校通信研修「中国語Ⅰ」の研修実施委託", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/180323-4.htm"},
    {title: "平成30年度税務大学校において使用する教材等の刷成", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/180323-1.htm"},
    {title: "税務大学校研修において使用する図書の購入(第1回)", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/180316-1.htm"},
    {title: "平成30年度税務大学校和光校舎乾式複写用紙(再生紙)の購入", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/180302-3.htm"},
    {title: "平成30年度一般廃棄物及びリサイクル廃棄物処理業務", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/180302-1.htm"},
    {title: "平成30年度定期刊行物の購入(区分）１、区分２)", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/180302.htm"},
    {title: "税務大学校研修において使用する図書の購入(第11回)", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/180216-1.htm"},
    {title: "平成30年度消耗品の購入(区分1、区分2）", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/180216-2.htm"},
    {title: "平成30年度印刷機用消耗品の購入", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/180216-3.htm"},
    {title: "平成30年度版税務大学校講本（税法編）等の刷成", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/180209.htm"},
    {title: "平成30年度専門官基礎研修及び社会人基礎研修における簿記研修の実施委託業務", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/180125.htm"},
    {title: "税務大学校和光校舎階段教室ほか音響制御機器等更新業務", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/171201-1.htm"},
    {title: "平成30年度版税務大学校講本（基礎編）等の刷成", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/171120-1.htm"},
    {title: "税務大学校和光校舎　教室用固定椅子の更新作業", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/171117-1.htm"},
    {title: "税務大学校研修において使用する図書の購入（第6回）（区分１、区分２）", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/171110.htm"},
    {title: "税務大学校和光校舎　学寮ベッドマットレスの購入等", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/171110-2.htm"},
    {title: "洗濯機等の購入等", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/171110-3.htm"},
    {title: "平成29年度本稿短期研修「ＩＣＴ調査特別」の実施委託", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/171026.htm"},
    {title: "複合機等の購入等（区分１、区分２）", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/171012-02.htm"},
    {title: "印刷機等の購入等（区分１、区分２）", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170906.htm"},
    {title: "税務大学校研修において使用する図書の購入（第6回）（区分１、区分２）", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170804.htm"},
    {title: "統計・解析ソフト（SPSS等）を使用した研修の実施委託", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170727.htm"},
    {title: "170627-001", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170627-001.htm"},
    {title: "平成29年度税務大学校和光校舎　定期健康診断業務の委託", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170623.htm"},
    {title: "平成29年度本稿短期研修「情報システム（SE）」の研修実施委託", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170609-4.htm"},
    {title: "学寮各棟の雑排水管高圧洗浄等業務", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170609-3.htm"},
    {title: "170605-1", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170605-1.htm"},
    {title: "税務訴訟資料第266号の作成", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170512.htm"},
    {title: "平成29年度本校長期研修「ＩＣＴの基礎知識」の研修実施委託（区分１・区分２）", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170420-1.htm"},
    {title: "170405-001", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170405-001.htm"},
    {title: "平成29年度　税務大学校通信研修「中国語Ⅰ」の研修実施委託", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170317-2.htm"},
    {title: "平成29年度　税務大学校通信研修「韓国語Ⅰ」の研修実施委託", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170317-1.htm"},
    {title: "170315-001", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170315-001.htm"},
    {title: "平成29年度税務大学校において使用する教材等の刷成", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170309-2.htm"},
    {title: "170303-2", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170303-2.htm"},
    {title: "170223-002", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170223-002.htm"},
    {title: "170223-001", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170223-001.htm"},
    {title: "170216-001", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170216-001.htm"},
    {title: "170215", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170215.htm"},
    {title: "160209-2", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160209-2.htm"},
    {title: "161116-1", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170127.htm"},
    {title: "160114-1", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/170125.htm"},
    {title: "161220-1", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/161220-1.htm"},
    {title: "161027-1", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/161201-1.htm"},
    {title: "161116-1", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/161116-1.htm"},
    {title: "161110-1", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/161110-1.htm"},
    {title: "161027-1", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/161027-1.htm"},
    {title: "161026", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/161026.htm"},
    {title: "161018", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/161018.htm"},
    {title: "160914", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160914.htm"},
    {title: "160728-1", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160902.htm"},
    {title: "160901", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160901.htm"},
    {title: "160728-1", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160728-1.htm"},
    {title: "160624", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160624.htm"},
    {title: "160616", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160616.htm"},
    {title: "160608", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160608.htm"},
    {title: "160607-2", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160607-2.htm"},
    {title: "160601", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160601.htm"},
    {title: "160530-1", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160530-1.htm"},
    {title: "160527", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160527.htm"},
    {title: "160525", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160525.htm"},
    {title: "160512", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160512.htm"},
    {title: "160407-2", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160407-2.htm"},
    {title: "160407-1", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160407-1.htm"},
    {title: "160406-2", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160406-2.htm"},
    {title: "160406-1", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160406-1.htm"},
    {title: "160331-2", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160331-2.htm"},
    {title: "160331-1", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160331-1.htm"},
    {title: "160318-1", url: "https://www.nta.go.jp/about/organization/ntc/chotatsu/buppin/koukoku/160318-1.htm"}
]